version: "3"

services:
  db:
    container_name: lamp-docker-db
    image: mysql:latest
    restart: "always"
    environment:
      - MYSQL_DATABASE_NAME= lamp_docker
      - MYSQL_USER= lamp_user
      - MYSQL_PASSWORD= lamp_password
      - MYSQL_ALLOW_EMPTY_PASSWORD= 1
  web:
    image: php:8.2.12-apache-bookworm
    restart: "always"
    volumes:
      - './www:/var/www/html'
    ports:
      - 8088:80
      - 4443:443
  phpadmin:
    image: phpmyadmin/phpmyadmin
    restart: "always"
    ports:
     - 8188:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root